# URL: (adicione este arquivo no repositório)
# Workflow: quando houver push na branch integrate-templates-references, o workflow atualiza o index.html em main.
# Observação: ele usa o GITHUB_TOKEN (permissões de conteúdo) para escrever em main.
# ⚠️ AVISO: A branch integrate-templates-references atualmente contém um index.html corrompido/placeholder.
# Este workflow deve ser usado apenas após correção dessa branch ou modificado para usar outra branch fonte.
name: Auto deploy index.html to main

on:
  push:
    branches:
      - integrate-templates-references
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  deploy-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch (main)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch source branch
        run: |
          git fetch origin integrate-templates-references:refs/remotes/origin/integrate-templates-references

      - name: Extract index.html from source branch
        run: |
          git checkout origin/integrate-templates-references -- index.html || true
          # If file doesn't exist in source, this won't fail due to "|| true"

      - name: Show diff (for logs)
        run: |
          git status --porcelain
          git --no-pager diff --name-only || true

      - name: Commit and push updated index.html to main (if changes)
        run: |
          if git status --porcelain | grep -q 'index.html'; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add index.html
            git commit -m "chore(deploy): update index.html from integrate-templates-references [auto]"
            git push origin main
            echo "index.html updated and pushed to main"
          else
            echo "No changes to index.html; nothing to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Optionally publish to GitHub Pages (if using pages and source=main)
        if: always()
        run: echo "If you use GitHub Pages from main branch, the updated index.html will be served automatically."